
name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # Run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update metrics
        uses: BalaM314/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          plugins_errors_fatal: yes

          # Options
          user: BalaM314
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/India

          # Achievements
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 0

          # Activity
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_visibility: public

          # Issue and PR follow ups
          plugin_followup: yes
          plugin_followup_sections: repositories, user

          # Habits
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes

          # Isometric Calendar
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Languages
          plugin_languages: yes
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 4%
          plugin_languages_skipped: mindustry-antigrief/mindustry-client

          # Code changes
          plugin_lines: yes

          # People (followers and such)
          # plugin_people: yes
          # plugin_people_limit: 28
          # plugin_people_size: 28
          # plugin_people_types: followers, following

          # Stargazers
          plugin_stargazers: yes

          # Projects
          plugin_projects: yes
          plugin_projects_limit: 4

